// <auto-generated />
namespace HCL.MVC.Week6.Day1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class stock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stock));
        
        string IMigrationMetadata.Id
        {
            get { return "201910040516317_stock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
